name: Test Suite

# Run against all commits and pull requests.
on:
  schedule:
    - cron: '0 0 * * *'
  push:
  pull_request:

jobs:
  test_matrix:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.0
          - 3.1
          - 3.2

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec

  rubocop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rake rubocop

# TODO: Add code coverage testing (coveralls)
# TODO: Add documentation/maintainability testing?
# TODO: Add dependency testing? (bundle audit)

  finish:
    runs-on: ubuntu-latest
    needs: [ test_matrix, rubocop ]
    steps:
      - name: Wait for status checks
        run: echo "All Green!"
