name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_matrix:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.5.8
          - 2.6.6
          - 2.7.2
          - 3.0.0

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec
      - name: Run rubocop
        run: bundle exec rake rubocop

  test:
    runs-on: ubuntu-latest
    needs: [test_matrix]
    steps:
      - name: Wait for status checks
        run: echo "All Green!"
